INSERT INTO EVENT_TYPE VALUES ('M', 'MEETING');
INSERT INTO EVENT_TYPE VALUES ('B', 'BIRTHDAY');
INSERT INTO EVENT_TYPE VALUES ('H', 'HOLIDAY');
INSERT INTO EVENT_STATUS VALUES ('A', 'ACCEPTED');
INSERT INTO EVENT_STATUS VALUES ('R', 'REJECTED');
INSERT INTO EVENT_STATUS VALUES ('N', 'NEUTRAL');