DROP TABLE IF EXISTS EVENT_TYPE;
CREATE TABLE EVENT_TYPE (
EVENT_TYPE_ID INT PRIMARY KEY,
EVENT_TYPE_NAME VARCHAR(50),
ALL_DAY_EVENT VARCHAR(1),
IS_HOLIDAY_IND VARCHAR(1)
);
DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM (
ROOM_ID VARCHAR(50) PRIMARY KEY,
BLOCK_NUMBER VARCHAR(50) NOT NULL,
FLOOR_NUMBER VARCHAR(50) NOT NULL
);
DROP TABLE IF EXISTS USER_INFO;
CREATE TABLE USER_INFO (
USER_ID VARCHAR(20) PRIMARY KEY,
USER_NAME VARCHAR(50)
);
DROP TABLE IF EXISTS EVENT;
CREATE TABLE EVENT (
EVENT_ID INT PRIMARY KEY,
EVENT_TYPE_ID VARCHAR(50),
EVENT_TITLE VARCHAR(50),
EVENT_START_TIME TIMESTAMP,
EVENT_DURATION INT,
ROOM_ID VARCHAR(50) ,
ORGANISER_ID VARCHAR(20)
);

DROP TABLE IF EXISTS EVENT_USER;
CREATE TABLE EVENT_USER (
EVENT_USER_ID INT PRIMARY KEY,
EVENT_ID VARCHAR(50) ,
USER_ID VARCHAR(50) ,
USER_STATUS VARCHAR(10)
);