DROP TABLE IF EXISTS EVENT_TYPE;
CREATE TABLE EVENT_TYPE (
EVENT_TYPE_ID VARCHAR(1) PRIMARY KEY,
EVENT_TYPE_NAME VARCHAR(20)
);

DROP TABLE IF EXISTS EVENT_STATUS;
CREATE TABLE EVENT_STATUS (
EVENT_STATUS_ID VARCHAR(1) PRIMARY KEY,
EVENT_STATUS_NAME VARCHAR(20)
);

DROP TABLE IF EXISTS EVENT;
CREATE TABLE EVENT (
EVENT_ID IDENTITY PRIMARY KEY,
EVENT_TYPE_ID VARCHAR(1),
TITLE VARCHAR(50),
START_TIME TIMESTAMP,
END_TIME TIMESTAMP,
OWNER_ID VARCHAR(20)
);

DROP TABLE IF EXISTS EVENT_USER;
CREATE TABLE EVENT_USER (
EVENT_USER_ID IDENTITY PRIMARY KEY,
EVENT_ID INT,
USER_ID VARCHAR(20),
START_TIME TIMESTAMP,
END_TIME TIMESTAMP,
USER_STATUS VARCHAR(20)
);

DROP TABLE IF EXISTS EVENT_ROOM;
CREATE TABLE EVENT_ROOM (
EVENT_ROOM_ID IDENTITY PRIMARY KEY,
ROOM_ID VARCHAR(20),
EVENT_ID INT,
START_TIME TIMESTAMP,
END_TIME TIMESTAMP
);